"""vector embedding

Revision ID: b094b8589bd9
Revises: 2fde557f6ffd
Create Date: 2026-03-14 01:28:54.155280

"""

from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b094b8589bd9"
down_revision: Union[str, Sequence[str], None] = "2fde557f6ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("turns", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("index", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_embeddings_doc_id"), "embeddings", ["doc_id"], unique=True)
    op.create_index(op.f("ix_embeddings_index"), "embeddings", ["index"], unique=False)
    op.add_column(
        "data_sources", sa.Column("freshness_ttl_seconds", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "data_sources",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "data_sources",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "schema_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "uq_schema_snapshot_source_version",
        "schema_snapshots",
        ["data_source_id", "version"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_schema_snapshot_source_version", "schema_snapshots", type_="unique"
    )
    op.alter_column(
        "schema_snapshots",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "data_sources",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "data_sources",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("data_sources", "freshness_ttl_seconds")
    op.drop_index("ix_embeddings_index_embedding", table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_index"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_doc_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_table("chat_sessions")
    # ### end Alembic commands ###
