from enum import Enum

# Execution
DEFAULT_TIMEOUT_SECONDS = 5
MAX_REFLECTION_RETRIES = 2

# PolicyEngine
DEFAULT_AUTOLIMIT = 100
MAX_LIMIT_ALLOWED = 1000


class EngineState(str, Enum):
    INIT = "INIT"
    PLAN = "PLAN"
    QUERY_GENERATION = "QUERY_GENERATION"
    VALIDATION = "VALIDATION"
    EXECUTION = "EXECUTION"
    REFLECTION = "REFLECTION"
    DONE = "DONE"
    FAILED = "FAILED"


class DatabaseDialect(str, Enum):
    POSTGRES = "POSTGRES"
    MYSQL = "MYSQL"
    SQLITE = "SQLITE"
    MSSQL = "MSSQL"
    MONGODB = "MONGODB"
    DYNAMODB = "DYNAMODB"
    NEO4J = "NEO4J"
    REDIS = "REDIS"
    CASSANDRA = "CASSANDRA"
    SNOWFLAKE = "SNOWFLAKE"
    BIGQUERY = "BIGQUERY"
    CLICKHOUSE = "CLICKHOUSE"
    DUCKDB = "DUCKDB"
