from enum import Enum


class EngineState(str, Enum):
    INIT = "INIT"
    PLAN = "PLAN"
    SCHEMA_RETRIEVAL = "SCHEMA_RETRIEVAL"
    QUERY_GENERATION = "QUERY_GENERATION"
    VALIDATION = "VALIDATION"
    EXECUTION = "EXECUTION"
    REFLECTION = "REFLECTION"
    DONE = "DONE"
    FAILED = "FAILED"


class DatabaseDialect(str, Enum):
    POSTGRES = "POSTGRES"
    # MYSQL = "MYSQL"
    # SQLITE = "SQLITE"
    # MSSQL = "MSSQL"


DEFAULT_TIMEOUT_SECONDS = 5
DEFAULT_AUTOLIMIT = 100
MAX_LIMIT_ALLOWED = 1000
MAX_REFLECTION_RETRIES = 2
